const PRODUCT_ADD_REQUEST = "PRODUCT_ADD_REQUEST";
const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS";
const PRODUCT_ADD_ERROR = "PRODUCT_ADD_ERROR";
const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
const PRODUCT_LIST_ERROR = "PRODUCT_LIST_ERROR";
const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
const PRODCUT_DELETE_ERROR = "PRODCUT_DELETE_ERROR";
const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
const PRODUCT_DETAIL_ERROR = "PRODUCT_DETAIL_ERROR";
const PRODCUT_EDIT_REQUEST = "PRODCUT_EDIT_REQUEST";
const PRODCUT_EDIT_SUCCESS = "PRODCUT_EDIT_SUCCESS";
const PRODCUT_EDIT_ERROR = "PRODCUT_EDIT_ERROR";
const FIND_FEATURED_PRODUCT_REQUEST = "FIND_FEATURED_PRODUCT_REQUEST";
const FIND_FEATURED_PRODUCT_SUCCESS = "FIND_FEATURED_PRODUCT_SUCCESS";
const FIND_FEATURED_PRODUCT_ERROR = "FIND_FEATURED_PRODUCT_ERROR";
const PRODUCT_REVIEW_REQUEST = "PRODUCT_REVIEW_REQUEST";
const PRODUCT_REVIEW_SUCCESS = "PRODUCT_REVIEW_SUCCESS";
const PRODUCT_REVIEW_ERROR = "PRODUCT_REVIEW_ERROR";

export {
  PRODUCT_ADD_REQUEST,
  PRODUCT_ADD_SUCCESS,
  PRODUCT_ADD_ERROR,
  PRODUCT_LIST_REQUEST,
  PRODUCT_LIST_SUCCESS,
  PRODUCT_LIST_ERROR,
  PRODUCT_DELETE_REQUEST,
  PRODUCT_DELETE_SUCCESS,
  PRODCUT_DELETE_ERROR,
  PRODUCT_DETAIL_REQUEST,
  PRODUCT_DETAIL_SUCCESS,
  PRODUCT_DETAIL_ERROR,
  PRODCUT_EDIT_REQUEST,
  PRODCUT_EDIT_SUCCESS,
  PRODCUT_EDIT_ERROR,
  FIND_FEATURED_PRODUCT_REQUEST,
  FIND_FEATURED_PRODUCT_SUCCESS,
  FIND_FEATURED_PRODUCT_ERROR,
  PRODUCT_REVIEW_REQUEST,
  PRODUCT_REVIEW_SUCCESS,
  PRODUCT_REVIEW_ERROR,
};
