const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";
const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
const USER_SIGNIN_ERROR = "USER_SIGNIN_ERROR";
const USER_ADD_CART_REQUEST = "USER_ADD_CART_REQUES";
const USER_ADD_CART_SUCCESS = "USER_ADD_CART_SUCCESS";
const USER_ADD_CART_ERROR = "USER_ADD_CART_ERROR";
const USER_ITEM_NUMBER_REQUEST = "USER_ITEM_NUMBER_REQUEST";
const USER_ITEM_NUMBER_SUCCESS = "USER_ITEM_NUMBER_SUCCESS";
const USER_ITEM_NUMBER_ERROR = "USER_ITEM_NUMBER_ERROR";
const USER_REMOVE_CART_REQUEST = "USER_REMOVE_CART_REQUEST";
const USER_REMOVE_CART_SUCCESS = "USER_REMOVE_CART_SUCCESS";
const USER_REMOVE_CART_ERROR = "USER_REMOVE_CART_ERROR";
const USER_ITEM_QTY_REQUEST = "USER_ITEM_QTY_REQUEST";
const USER_ITEM_QTY_SUCCESS = "USER_ITEM_QTY_SUCCESS";
const USER_ITEM_QTY_ERROR = "USER_ITEM_QTY_ERROR";
const USER_ITEM_SIZE_REQUEST = "USER_ITEM_SIZE_REQUEST";
const USER_ITEM_SIZE_SUCCESS = "USER_ITEM_SIZE_SUCCESS";
const USER_ITEM_SIZE_ERROR = "USER_ITEM_SIZE_ERROR";
const USER_ADDRESS_SAVE = "USER_ADDRESS_SAVE";
const USER_PAYMENT_SAVE = "USER_PAYMENT_SAVE";
const USER_ORDER_REQUEST = "USER_ORDER_REQUEST";
const USER_ORDER_SUCCESS = "USER_ORDER_SUCCESS";
const USER_ORDER_ERROR = "USER_ORDER_ERROR";
const USER_ORDER_DETAIL_REQUEST = "USER_ORDER_DETAIL_REQUEST";
const USER_ORDER_DETAIL_SUCCESS = "USER_ORDER_DETAIL_SUCCESS";
const USER_ORDER_DETAIL_ERROR = "USER_ORDER_DETAIL_ERROR";
const USER_STRIPE_REQUEST = "USER_STRIPE_REQUEST";
const USER_STRIPE_SUCCESS = "USER_STRIPE_SUCCESS";
const USER_STRIPE_ERROR = "USER_STRIPE_ERROR";
const USER_ORDERS_REQUEST = "USER_ORDERS_REQUEST";
const USER_ORDERS_SUCCESS = "USER_ORDERS_SUCCESS";
const USER_ORDERS_ERROR = "USER_ORDERS_ERROR";
const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";
const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
const GET_ALL_ORDERS_ERROR = "GET_ALL_ORDERS_ERROR";
const USER_ORDERS_UPDATE_REQUEST = "USER_ORDERS_UPDATE_REQUEST";
const USER_ORDERS_UPDATE_SUCCESS = "USER_ORDERS_UPDATE_SUCCESS";
const USER_ORDERS_UPDATE_ERROR = "USER_ORDERS_UPDATE_ERROR";
const USER_CONTACT_FORM_REQUEST = "USER_CONTACT_FORM_REQUEST";
const USER_CONTACT_FORM_SUCCESS = "USER_CONTACT_FORM_SUCCESS";
const USER_CONTACT_FORM_ERROR = "USER_CONTACT_FORM_ERROR";
const USER_LOGOUT = "USER_LOGOUT";

export {
  USER_REGISTER_REQUEST,
  USER_REGISTER_SUCCESS,
  USER_REGISTER_ERROR,
  USER_SIGNIN_REQUEST,
  USER_SIGNIN_SUCCESS,
  USER_SIGNIN_ERROR,
  USER_ADD_CART_REQUEST,
  USER_ADD_CART_SUCCESS,
  USER_ADD_CART_ERROR,
  USER_ITEM_NUMBER_REQUEST,
  USER_ITEM_NUMBER_SUCCESS,
  USER_ITEM_NUMBER_ERROR,
  USER_REMOVE_CART_REQUEST,
  USER_REMOVE_CART_SUCCESS,
  USER_REMOVE_CART_ERROR,
  USER_ITEM_QTY_REQUEST,
  USER_ITEM_QTY_SUCCESS,
  USER_ITEM_QTY_ERROR,
  USER_ITEM_SIZE_REQUEST,
  USER_ITEM_SIZE_SUCCESS,
  USER_ITEM_SIZE_ERROR,
  USER_ADDRESS_SAVE,
  USER_PAYMENT_SAVE,
  USER_ORDER_REQUEST,
  USER_ORDER_SUCCESS,
  USER_ORDER_ERROR,
  USER_ORDER_DETAIL_REQUEST,
  USER_ORDER_DETAIL_SUCCESS,
  USER_ORDER_DETAIL_ERROR,
  USER_STRIPE_REQUEST,
  USER_STRIPE_SUCCESS,
  USER_STRIPE_ERROR,
  USER_ORDERS_REQUEST,
  USER_ORDERS_SUCCESS,
  USER_ORDERS_ERROR,
  GET_ALL_ORDERS_REQUEST,
  GET_ALL_ORDERS_SUCCESS,
  GET_ALL_ORDERS_ERROR,
  USER_ORDERS_UPDATE_REQUEST,
  USER_ORDERS_UPDATE_SUCCESS,
  USER_ORDERS_UPDATE_ERROR,
  USER_CONTACT_FORM_REQUEST,
  USER_CONTACT_FORM_SUCCESS,
  USER_CONTACT_FORM_ERROR,
  USER_LOGOUT,
};
